version: "2"
services:
  rabbitmq:
    image: "rabbitmq:3.6-management"
    ports:
      # host:container
      - "8081:15672"
      - "15674:15674"
      - "61613:61613"
    environment:
      - RABBITMQ_ERLANG_COOKIE=Pu3Ah#qui
  workshop:
    build: .
    ports:
      # host:container
      - "8080:80"
    links:
      - rabbitmq
    volumes:
      - ./:/var/www/html/
