old_sound_rabbit_mq:
    connections:
        default:
            host:     '%rabbitmq_host%'
            port:     '%rabbitmq_port%'
            user:     '%rabbitmq_user%'
            password: '%rabbitmq_password%'
            vhost:    '%rabbitmq_vhost%'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false
            # requires php-amqplib v2.4.1+
            heartbeat: 0
    producers:
        direct:
            connection:       default
            exchange_options: {name: 'direct-exchange', type: direct}
            queue_options:    {name: 'direct-queue'}
    consumers:
        direct:
            connection:       default
            exchange_options: {name: 'direct-exchange', type: direct}
            queue_options:    {name: 'direct-queue'}
            callback:         app.rabbitmq.consumer.direct